/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppSettings = IDL.Record({
  'offset' : IDL.Text,
  'location' : IDL.Text,
});
export const SermonData = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'date' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAppSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AppSettings)],
      ['query'],
    ),
  'getCallerAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestCachedSermon' : IDL.Func([], [SermonData], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshAndGetLatestSermon' : IDL.Func([], [SermonData], []),
  'saveCallerAppSettings' : IDL.Func([AppSettings], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppSettings = IDL.Record({
    'offset' : IDL.Text,
    'location' : IDL.Text,
  });
  const SermonData = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'date' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAppSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AppSettings)],
        ['query'],
      ),
    'getCallerAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestCachedSermon' : IDL.Func([], [SermonData], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshAndGetLatestSermon' : IDL.Func([], [SermonData], []),
    'saveCallerAppSettings' : IDL.Func([AppSettings], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };