/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppSettings = IDL.Record({
  'offset' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const AppRelease = IDL.Record({
  'version' : IDL.Text,
  'updatedAt' : Time,
  'storeUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAppSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AppSettings)],
      ['query'],
    ),
  'getCallerAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestAppRelease' : IDL.Func([], [IDL.Opt(AppRelease)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerAppSettings' : IDL.Func([AppSettings], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLatestAppRelease' : IDL.Func([AppRelease], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppSettings = IDL.Record({
    'offset' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const AppRelease = IDL.Record({
    'version' : IDL.Text,
    'updatedAt' : Time,
    'storeUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAppSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AppSettings)],
        ['query'],
      ),
    'getCallerAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestAppRelease' : IDL.Func([], [IDL.Opt(AppRelease)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerAppSettings' : IDL.Func([AppSettings], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLatestAppRelease' : IDL.Func([AppRelease], [], []),
  });
};

export const init = ({ IDL }) => { return []; };